# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_seventh', '0002_auto_20180226_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
